<template><div><h3 id="powderblade" tabindex="-1"><a class="header-anchor" href="#powderblade"><span>Powderblade</span></a></h3>
<p>One of the more commonplace weapons for infantry-hunting scriptlighters, they are a wide class of devices that operate on the fundamental principle of constructing a monocrystal diamond blade out of powerdized carbon. The resulting blade channels gimynfire exceedingly well, almost serving to become a blade of pure gimynfire. In addition to carbon’s exceptional responsiveness to gimynfire control, coupling allows the diamond’s covalent bonds to loosen and gain elasticity, making it more suitable for a blade.</p>
<p>All of the above factors serve to make the blade roughly equivalent to a traditional silver-steel blade, but this is not the true purpose of powderblades. Instead, they serve as a countermeasure to heavyweight scriptlighters and their high-flashpoint armor. When coupled armor is struck with a powderblade, there is naturally a combustion event, resulting in the decoupling of the blade and the draining of the armor’s coupling charge. However, the pure-crystal carbon structure of the powderblade is easily re-coupled and reformed, whereas the high-resistance armor would require full focus to recharge. The shattering blade also means that an attack can be fully followed through, maintaining the attacker’s speed. In this way, the heavyweight can be steadily worn down for a chance at victory.</p>
<p>The main design of a powderblade is, appropriately, in the handle, which looks much too long for the short, knife-like blade stem. The two marks of a well-crafted powderblade are the efficiency of the core kindlegem, and the crystal purity of the diamond dust. The more efficient the kindlegem is, the more gimynfire can be run through the blade; the purer the crystals, the easier they can be recoupled.</p>
<p>Powderblades may come in numerous forms, each depending on the efficiency of their creator. Some of the well designed versions are more like swarms of scintillating darts when fighting infantry, but can coalesce into a blade for close-quarters combat; this melee configuration being necessary for scriptlighter conflict as dart weapons could be easily challenged and counter-coupled.</p>
<p>Powderblades are no slouch when it comes to other areas of use as well. Since the diamond blade is able to exude a highly dense gimynfire cloud just around the blade, it's possible to learn to use this cloud to temporarily couple and rend any material the blade strikes, making it like a traditional sword. The technique requires extreme concentration and timing at first, but becomes second nature with practice or well-made kindlegems.</p>
</div></template>


