<template><div><h2 id="biological-conventions" tabindex="-1"><a class="header-anchor" href="#biological-conventions"><span>Biological Conventions</span></a></h2>
<h3 id="photosynthesis" tabindex="-1"><a class="header-anchor" href="#photosynthesis"><span>Photosynthesis</span></a></h3>
<p>Life on Aliffrüme evolved under a violet-peaking sun. This means that purple, specifically bacteriorhodopsin won out as the dominant color to photosynthesize with during early evolutionary stages. Plants which utilize this photosynthesis method don't need much water, since the bacteriorhodopsin reaction is extremely simple and doesn't use water or produce oxygen.</p>
<h3 id="pneumivorosity" tabindex="-1"><a class="header-anchor" href="#pneumivorosity"><span>Pneumivorosity</span></a></h3>
<p>Through the utilization of various porphyrin-based pigments, certain plants are able to consume soulfire for various effects. Most common is as a replacement for photosynthetic pigments, allowing the organism to grow much larger and without reliance on sunlight. Less common is to directly drive the ATP cycle, although this method is unsuited to droughts of soulfire or fluctuations in its intensity.</p>
<h3 id="sex-and-epigenetics" tabindex="-1"><a class="header-anchor" href="#sex-and-epigenetics"><span>Sex and Epigenetics</span></a></h3>
<p>Biological sex for sentient species is handled somewhat differently from the majority of other true species, due to global distribution yet frequent mingling and intense radiation. The “species” of a sentient is something like a second sex chromosome pair. Consider the following case:<br>
An Áren male and Yejian female, both homogenous, have children. Any males born would be Áren, with a recessive Yejian encoding. Any females born would be Yejian, with a recessive Áren encoding. Intersex children or other genetic deviations tend to result in infertile hybrids, due to the volatility of the system.<br>
Note that these results depend on species group, not race. Thus, an Áren and Muintaferan could give birth to children of either gender and race. Additionally, if both have a recessive encoding for the same species, it’s possible their children may be born of that species instead.</p>
<h3 id="sentient-species" tabindex="-1"><a class="header-anchor" href="#sentient-species"><span>Sentient “Species”</span></a></h3>
<p>The different “species” of sentients are actually more similar to a multitude of different subspecies groups for two or three species, as intense radiation has spurred rapid specialization and adaptation to the varied environments of Aliffrüme. The four known are the Llantakúna,  Kuthjïuman, Tiangengzhe, and Zäkhisny. There are, however, many ill-substantiated reports of a peculiar tall-eared race hidden among the glaciers of the southern continent, often referred to as the Rokajun.</p>
</div></template>


