<template><div><h2 id="pneumasensitivity" tabindex="-1"><a class="header-anchor" href="#pneumasensitivity"><span>Pneumasensitivity</span></a></h2>
<p>Every sentient being on Aliffrüme has some level of pneumasensitivity, or the ability to sense and/or feel [[Soulfire|soulfire]] and [[Soulfire#Sparks|sparks]]. Organs that provide this sense are called pneumasensors, and typically resemble rod or cone cells but with guanine lattices instead of modified retinal discs. These organs come in two types:</p>
<h3 id="pyrrhoreceptors" tabindex="-1"><a class="header-anchor" href="#pyrrhoreceptors"><span>Pyrrhoreceptors</span></a></h3>
<p>A type of specialized neuron found in all living creatures that can determine how much soulfire it holds, serving numerous purposes throughout the body. The most relevant, however, is in the ears. When macro-scale vibrations in the conscious plane push against the [[Soul|halo]], the reaction “shunts” some soulfire to [[Infusion|infuse]] nearby matter, which can be detected by sensitive pyrrhoreceptors.</p>
<p>In this way, a sense of soulfire “hearing” is created by placing pyrrhoreceptors through the halo’s border, allowing for the detection of organic movement and especially the usage of soulfire. It also works as a unique identifier for an individual, like a second voice. Due to their nature, these sensors are often found in the ear tips, and a heightened sensitivity requires the lengthening of the ears, allowing for the detection of longer wavelengths.</p>
<p>However, a heightened sensitivity means a higher risk of muting or damaging the receptors in soulfire-dense environments, especially with the limited protection cartilage provides. Thus some species that evolved in these soulfire-dense environments, such as the [[Kuthjïuman#Kaithurhi|Kaithurhi]], instead grow dedicated horns of modified bone surrounded in collagen. The bone, in addition to holding marrow, protects strips of pyrrhoreceptors that grant excellent directional hearing at the cost of sensitivity.</p>
<h3 id="sparkcatchers" tabindex="-1"><a class="header-anchor" href="#sparkcatchers"><span>Sparkcatchers</span></a></h3>
<p>A type of neuron found in sentient creatures, able to detect sparks, with a similar structure to rod cells. Though soulfire can be detected through the intuitive extensions of the 5 main senses, sparks exist in the material plane and thus necessitate specialized sensors. Detecting sparks allows for an early warning system against firekeeping predators, with many sentients even learning to predict the movements of others and even the effects of engrams based upon the timing and distribution of sparks.</p>
</div></template>


