<template><div><h1 id="biogeography" tabindex="-1"><a class="header-anchor" href="#biogeography"><span><strong>Biogeography</strong></span></a></h1>
<h2 id="biomes" tabindex="-1"><a class="header-anchor" href="#biomes"><span>Biomes</span></a></h2>
<h3 id="copperleaf-forests" tabindex="-1"><a class="header-anchor" href="#copperleaf-forests"><span>Copperleaf Forests</span></a></h3>
<p>A biome where gimyndine deposits have been brought up close to the surface, and into close proximity with dense life, typically tropical or temperate rainforests. The result is a biome overflowing with soulfire all aligned to one wavelength by spontaneous synchrony, which can be even more damaging than disharmonic soulfire.<br>
Life in these forests is often well-adapted to the use of ambient soulfire created by the gimyndine harmonics, when normally it could not create it. Plants self-sustain, animals use low-gravity jumps and mirages, and even the water sparkles an enchanting cyan.<br>
All plant life in the copperleaf forests is fotivorous, meaning that they utilize soulfire to drive glucose production. The pigment central to this is phycocyanin, which is typically a sapphire blue, but fluoresces white when in high soulfire concentrations.<br>
Due to the egregious amounts of dense soulfire given off by the pelygwyr and animarchaea population, certain rivers can become coated in a thick, glowing layer of flowing soulfire. Such rivers are called life-rivers, and are important recharging sites for nearby animal life. If one is unfortunate enough to fall completely in, they risk succumbing to the intense soulfire, inducing lysis of their bodies, like a resonant frequency destroying a glass.</p>
<h3 id="stellar-plains" tabindex="-1"><a class="header-anchor" href="#stellar-plains"><span>Stellar Plains</span></a></h3>
<p>A region that covers northern Riihiya, and resembles an expansive pale-blue tundra sprinkled with the occasional lilypad-like violet tree. The region is permanently under thick snow cover, though it is not devoid of life. The snow pulses with bioluminescent extremophile algae, which use fotivorous processes to melt the snow around them for water and photosynthesize. The algae maintain a constant supply of soulfire by living in large colonies, and secreting highly nutritious and sweet compounds like sucrose and glucose. This, combined with the promise of water, attracts other life to these “snow-springs” while encouraging them to keep the algae alive.</p>
</div></template>


